backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título da Notícia", name: "title", widget: "string"}
      - {label: "Subtítulo / Resumo", name: "subtitle", widget: "string", required: false}
      - {label: "Data da Postagem", name: "date", widget: "datetime"}
      - {label: "Autor", name: "autor", widget: "string", default: "CG News Oficial"}
      - {label: "Categoria", name: "categoria", widget: "select", options: ["Últimas Notícias", "Polícia", "Trânsito", "Campo Grande", "Mato Grosso do Sul", "Brasil", "Mundo"]}
      - {label: "Foto de Capa", name: "image", widget: "image"}
      - {label: "Texto Completo da Notícia", name: "body", widget: "markdown"}
