backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Categoria", name: "categoria", widget: "select", options: ["Últimas Notícias", "Polícia", "Trânsito", "Campo Grande", "Mato Grosso do Sul", "Brasil", "Mundo"]}
      - {label: "Super Destaque", name: "super_destaque", widget: "boolean", required: false}
      - {label: "Destaque", name: "destaque", widget: "boolean", required: false}
      - {label: "Mídia da Notícia (Foto ou Vídeo)", name: "image", widget: "file", required: false, hint: "Envie uma foto ou um vídeo direto do seu celular"}
      - {label: "Fonte Mídia", name: "fonte_imagem", widget: "string", required: false}
      - {label: "Link do YouTube (Opcional)", name: "video", widget: "string", required: false}
      - {label: "Autor", name: "autor", widget: "string", required: false}
      - {label: "Data e Hora", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Subtítulo", name: "subtitle", widget: "string", required: false}
      - {label: "Texto", name: "body", widget: "markdown"}
      - {label: "Fonte", name: "fonte", widget: "string", required: false}
